# - Try to locate SDL2_mixer
# This module defines:
#
#  SDL2_MIXER_INCLUDE_DIR
#  SDL2_MIXER_LIBRARY
#  SDL2_MIXER_FOUND
#
# And the target:
#  SDL::SDL2_mixer
#

FIND_PATH(SDL2_MIXER_INCLUDE_DIR NAMES SDL_mixer.h PATH_SUFFIXES SDL2)

FIND_LIBRARY(SDL2_MIXER_LIBRARY NAMES SDL2_mixer)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL2_mixer REQUIRED_VARS SDL2_MIXER_LIBRARY SDL2_MIXER_INCLUDE_DIR)

MARK_AS_ADVANCED(SDL2_MIXER_INCLUDE_DIR SDL2_MIXER_LIBRARY)

ADD_LIBRARY(SDL::SDL2_mixer INTERFACE IMPORTED)
TARGET_INCLUDE_DIRECTORIES(SDL::SDL2_mixer INTERFACE ${SDL2_MIXER_INCLUDE_DIR})
TARGET_LINK_LIBRARIES(SDL::SDL2_mixer INTERFACE ${SDL2_MIXER_LIBRARY})
