# - Try to locate SDL2_ttf
# This module defines:
#
#  SDL2_TTF_INCLUDE_DIR
#  SDL2_TTF_LIBRARY
#  SDL2_TTF_FOUND
#
# And the target:
#  SDL::SDL2_ttf
#

FIND_PATH(SDL2_TTF_INCLUDE_DIR NAMES SDL_ttf.h PATH_SUFFIXES SDL2)

FIND_LIBRARY(SDL2_TTF_LIBRARY NAMES SDL2_ttf)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL2_ttf REQUIRED_VARS SDL2_TTF_LIBRARY SDL2_TTF_INCLUDE_DIR)

MARK_AS_ADVANCED(SDL2_TTF_INCLUDE_DIR SDL2_TTF_LIBRARY)

ADD_LIBRARY(SDL::SDL2_ttf INTERFACE IMPORTED)
TARGET_INCLUDE_DIRECTORIES(SDL::SDL2_ttf INTERFACE ${SDL2_TTF_INCLUDE_DIR})
TARGET_LINK_LIBRARIES(SDL::SDL2_ttf INTERFACE ${SDL2_TTF_LIBRARY})
