# - Try to locate SDL2_image
# This module defines:
#
#  SDL2_IMAGE_INCLUDE_DIR
#  SDL2_IMAGE_LIBRARY
#  SDL2_IMAGE_FOUND
#
# And the target:
#  SDL::SDL2_image

FIND_PATH(SDL2_IMAGE_INCLUDE_DIR NAMES SDL_image.h PATH_SUFFIXES SDL2)

FIND_LIBRARY(SDL2_IMAGE_LIBRARY NAMES SDL2_image)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL2_image REQUIRED_VARS SDL2_IMAGE_LIBRARY SDL2_IMAGE_INCLUDE_DIR)

MARK_AS_ADVANCED(SDL2_IMAGE_INCLUDE_DIR SDL2_IMAGE_LIBRARY)

ADD_LIBRARY(SDL::SDL2_image INTERFACE IMPORTED)
TARGET_LINK_LIBRARIES(SDL::SDL2_image INTERFACE ${SDL2_IMAGE_LIBRARY})
TARGET_INCLUDE_DIRECTORIES(SDL::SDL2_image INTERFACE ${SDL2_IMAGE_INCLUDE_DIR})
